In [1]:
import pandas as pd

In [2]:
#Reading csv
player_df = pd.read_csv('../static/Resources/teamsplayer.csv', encoding="ISO-8859-1")
player_df.head()

,Rk,Player,Age,G,GS,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,LeBron James,38,55,54,35.5,11.1,22.2,0.500,2.2,...,0.768,1.2,7.1,8.3,6.8,0.9,0.6,3.2,1.6,28.9
1,2,Anthony Davis,29,56,54,34.0,9.7,17.2,0.563,0.3,...,0.784,3.5,9.1,12.5,2.6,1.1,2.0,2.2,2.6,25.9
2,3,D'Angelo Russell,26,17,17,30.9,6.3,13.0,0.484,2.7,...,0.735,0.4,2.5,2.9,6.1,0.6,0.5,2.3,1.4,17.4
3,4,Dennis SchrÃ¶der,29,66,50,30.1,4.1,9.8,0.415,1.1,...,0.857,0.3,2.2,2.5,4.5,0.8,0.2,1.7,2.2,12.6
4,5,Austin Reaves,24,64,22,28.8,4.0,7.7,0.529,1.3,...,0.864,0.5,2.5,3.0,3.4,0.5,0.3,1.5,1.7,13.0

In [3]:
player_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      24 non-null     int64
 1   Player  24 non-null     object
 2   Age     24 non-null     int64
 3   G       24 non-null     int64
 4   GS      24 non-null     int64
 5   MP      24 non-null     float64
 6   FG      24 non-null     float64
 7   FGA     24 non-null     float64
 8   FG%     24 non-null     float64
 9   3P      24 non-null     float64
 10  3PA     24 non-null     float64
 11  3P%     24 non-null     float64
 12  2P      24 non-null     float64
 13  2PA     24 non-null     float64
 14  2P%     24 non-null     float64
 15  eFG%    24 non-null     float64
 16  FT      24 non-null     float64
 17  FTA     24 non-null     float64
 18  FT%     24 non-null     float64
 19  ORB     24 non-null     float64
 20  DRB     24 non-null     float64
 21  TRB     24 non-null     float64
 22  AST     24 non-null     float64
 23  STL     24 non-null     float64
 24  BLK     24 non-null     float64
 25  TOV     24 non-null     float64
 26  PF      24 non-null     float64
 27  PTS     24 non-null     float64
dtypes: float64(23), int64(4), object(1)
memory usage: 5.4+ KB

In [6]:
player_df.columns

Index(['Rk', 'Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
       '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [8]:
player_df = player_df.drop(columns = ['G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
                                      '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TOV', 'PF'
                                     ])
player_df.head()

KeyError: "['G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TOV', 'PF'] not found in axis"

In [9]:
player_df = player_df.fillna(0)
player_df.head()

   Rk            Player  Age   TRB  AST  STL  BLK   PTS
0   1      LeBron James   38   8.3  6.8  0.9  0.6  28.9
1   2     Anthony Davis   29  12.5  2.6  1.1  2.0  25.9
2   3  D'Angelo Russell   26   2.9  6.1  0.6  0.5  17.4
3   4  Dennis SchrÃ¶der   29   2.5  4.5  0.8  0.2  12.6
4   5     Austin Reaves   24   3.0  3.4  0.5  0.3  13.0

In [10]:
output=player_df.to_csv('../static/Resources/teamsplayer.csv', index=False)
output